version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-allopen
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: io.github.majusko:grpc-jwt-spring-boot-starter
    versions:
    - 1.0.7
